name: Read Hello File

on:
  push:
    branches:
      - main

jobs:
  read-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read and print hello.txt
        run: cat hello.txt
